### PR TITLE
INTG-528 Create release from commit that started workflow

### PR DESCRIPTION
**Pull request by ryan-breidenbach**
This change is pretty straightforward. How should we test this before merging this? Is that possible?

### CODE REVIEW

**Comment by davidaayers** [comment]
General comment unrelated to the contents of this work, our [standards](https://github.com/invitation-homes/technology-decisions/blob/main/0014-tracking-jira-issues-in-git.md) for jira linking say that _each_ commit should also include the Jira story identifier.

**Comment by ryan-breidenbach** [comment]
> General comment unrelated to the contents of this work, our [standards](https://github.com/invitation-homes/technology-decisions/blob/main/0014-tracking-jira-issues-in-git.md) for jira linking say that _each_ commit should also include the Jira story identifier.

It is, but I added it at the end of the commit message (old habit). Is there a reason to but the Jira story ID at the start of the commit message? That seems noisy, takes up precious characters in the commit title, and offers no value as far as I can tell. I think our tooling with discover the story ID anywhere in the message.

**Comment by davidaayers** [comment]
We can re-visit this in the TAG if we want, but after some vigorous and opinionated debate, this is where we landed, and keeping them in front was part of that decision. This was all before you joined, so maybe it's ripe to revisit :)

**Comment by davidaayers** [comment]
Much of that discussion can be viewed in this [PR](https://github.com/invitation-homes/technology-decisions/pull/18), where Ed asked the same question you just did 😆

**Comment by ryan-breidenbach** [comment]
OK. I will (reluctantly) update my commit messages. And for sure I think we should revisit this. From the ADR:

> Note that for both PR Titles & Commits, the Jira number should be the first thing on the first line of the title/commit, following by a space. No extra characters should be used to separate the Jira number from the rest of the text on the line.

Unless there is a reason for putting it first, I would argue for _not_ putting first in the commit message.

**Review by faisalkhanani — APPROVED** [review]

**Pull request merged**
